# Generated by Django 4.2.7 on 2025-01-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_categories_options_alter_categories_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='quantity',
        ),
        migrations.AddField(
            model_name='products',
            name='porcia',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Порция'),
        ),
    ]
